name: Ad Hoc Custom Builds

on:
  workflow_dispatch:

jobs:
  build-macos:
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit
    with:
      NIGHTLY: true

  build-windows:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      NIGHTLY: true

  release:
    needs: [build-macos, build-windows]
    # needs: [build-windows]
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      NIGHTLY: true
